version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
